[package]
name = "zeep"
version = "0.1.4"
authors = ["mibes <mibes@avaya.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14"
log = "0.4"
log4rs = "1"
Inflector = "0.11"
yaserde = "0.7"
yaserde_derive = "0.7"
clap = "3"
xml-rs = "0.8"
reqwest = { version = "0.11", features =["blocking"]}
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
zeep-lib = { path = "../zeep-lib"}